Repository mido/mido, pull requests merged in 2023-07, with the labels that each got.

#488 Separate GitHub workflow test steps
  .github/workflows/test.yml
  LICENSES/CC-BY-SA-3.0.txt
  logo/mido_shadow-vertical.png.license
  logo/mido_square-or-round.png.license
  pyproject.toml
Labels: enhancement, tooling

#465 Allow custom clock for MIDI playback
  mido/midifiles/midifiles.py
Labels: enhancement, feature:midifile

#499 Miscellaneous fixes around dependencies
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: enhancement, tooling

#501 Read the Docs configuration
  .readthedocs.yaml
  MANIFEST.in
Labels: enhancement, documentation, tooling

#503 Release automation prototype
  .github/workflows/documentation.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  docs/contributing.rst
  docs/glossary.rst
  pyproject.toml
Labels: enhancement, tooling

#286 Make `UnknownMetaMessage` robust to faulty MIDIs
  mido/midifiles/meta.py
Labels: feature:midifile

#520 Fix docs
  docs/index.rst
  docs/meta_message_types.rst
Labels: bug, documentation

#516 Add missing classifiers for PyPI
  pyproject.toml
Labels: tooling
